### ISSUE TITLE
Figure 2 image link

### ISSUE THREAD

**Issue by lazydino** [usnistgov/ucef#1]
Image link of figure 2 in https://github.com/usnistgov/ucef/blob/develop/docs/federatedtestbedarch/README.md seems to be broken?

**Comment by yogeshVU** [comment]
Actually the link is not broken, just that it is not rendered correctly given it is a pdf image file.
Here is the link: (https://github.com/usnistgov/ucef/blob/develop/docs/federatedtestbedarch/federation.pdf)
