### ISSUE TITLE
host os for VM

### ISSUE THREAD

**Issue by lazydino** [usnistgov/ucef#2]
I am not really familiar with Oracle virtual box. Would a host operating system of Ubuntu 16 equipped with 8 GB meory and 100GB hard drive suffice to run ucef VM? Do you have plan to provide docker containers instead of VM?

**Comment by yogeshVU** [comment]
You can run the oracle virtual box on the ubuntu 16 machine. 
You can change the amount memory assigned to the VM by configuring this section: https://github.com/usnistgov/ucef/blob/develop/build/machine.json#L11

**Comment by yogeshVU** [comment]
We are using VM since it provides a complete development environment with all the required packages for developing UCEF applications.

**Comment by lazydino** [comment]
Will definitely try ucef VM. Is CPSWT HLA template for seeding a WebGME model available separately?

**Comment by tpr1** [comment]
You can get the WebGME meta for HLA here: https://github.com/usnistgov/ucef-meta

Running `npm install` at the root of that repository will install WebGME.
