### ISSUE TITLE
Cannot find node?

### ISSUE THREAD

**Issue by lazydino** [usnistgov/ucef#3]
I follow the instructions [here](https://github.com/usnistgov/ucef/tree/develop/build) and build the vm, but the Vagrantfile doesn't seem to install 'node js ' or 'docker' inside the VM? 
![virtualbox_ucef 1 0 0-alpha_02_08_2017_11_44_07](https://user-images.githubusercontent.com/1158846/28889188-18dbaef2-7778-11e7-8f80-2b83b1bc655e.png)

Am I building the right stuffs with build/Vagrantfile ? Do I need to install those components myself?

**Comment by yogeshVU** [comment]
@lazydino : thanks for trying out. Can you make sure you have reached the end of the installation of the VM creation? (you can check that from the command prompt where the vagrant up --provision is issued).
Once successfully built, it should contain node and docker installed. Let us know, if you still encounter the above issue.

**Comment by lazydino** [comment]
so I should rebuild by running "vagrant up --provision" and also "vagrant reload" again?

**Comment by yogeshVU** [comment]
that will be a good approach

**Comment by lazydino** [comment]
Yes, it looks like I was too impatient, and just try the VM prematurely. The installation takes much longer than the previous time. Thanks!
