### ISSUE TITLE
workshop demo question

### ISSUE THREAD

**Issue by lazydino** [usnistgov/ucef#4]
https://github.com/usnistgov/ucef-samples/issues/1

**Comment by tpr1** [comment]
Did you run the `build.sh` script in the workspace folder?

**Comment by lazydino** [comment]
I think I did, but maven reports problem on building House. Attached is the part of output as the result running ./build.sh at cpswt/cpswt-samples/UCEFWorkshopExercise/workshop
![image](https://user-images.githubusercontent.com/1158846/29728778-2f42a088-898e-11e7-853e-d3d2fd4a344d.png)

**Comment by tpr1** [comment]
Replace the file at `HouseProject_generated/HouseProject-java-federates/HouseProject-impl-java/House/pom.xml` with this one https://github.com/usnistgov/ucef-samples/blob/develop/UCEFWorkshopExercise/workspace/resources/pom.xml and re-run `build.sh`

I added these two dependencies

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.8.5</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-yaml</artifactId>
            <version>2.8.5</version>
        </dependency>

**Comment by lazydino** [comment]
I run ./build with the new pom.xml, it won't complain but the .run.sh script doesn't give me two federates and reports connection refused? See attached screen shot.
![image](https://user-images.githubusercontent.com/1158846/29732552-e27331ea-899d-11e7-8b35-310c39585f74.png)

**Comment by tpr1** [comment]
The federate windows can hide each other when you use the run script. Did you check behind the three windows that did open to see if there were more hidden in the background?

There was an error in the run script causing connection refused fixed in this version https://github.com/usnistgov/ucef-samples/blob/develop/UCEFWorkshopExercise/run.sh

**Comment by lazydino** [comment]
Thanks! You are right, the federates windows are hidden behind. I replaced the run script, and I also tried ./runyourhouse.sh of "step 6", but something went wrong with the HouseConfig.json?

![image](https://user-images.githubusercontent.com/1158846/29785837-e65bab74-8bdd-11e7-9be7-f767fb5ff879.png)

**Comment by tpr1** [comment]
Copy this file https://github.com/usnistgov/ucef-samples/blob/develop/UCEFWorkshopExercise/workspace/resources/config.yml to `HouseProject_generated/HouseProject-java-federates/HouseProject-impl-java/House/conf/config.yml` and then re-run `build.sh`.

**Comment by lazydino** [comment]
Thanks for the help, I could complete the exercise now. So what happened when I invoke Federate Exporter the next time? Would some of the fixes mentioned in this thread got overwritten if I copy the extracted content?

**Comment by tpr1** [comment]
Yes, your working code will be overwritten.

I would recommend that you extract the federate exporter output to a different directory and copy the entire `HouseProject-impl-java` directory over from your working code. When you change your federate's publications and subscriptions, however, you will have to merge the two `House.java` files either using software or by hand.
